name: Release

on:
  push:
    tags: [ "v[0-9]+.*" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          target: x86_64-pc-windows-msvc
#          override: true
#      - run: cargo build --release --all-features

      - uses: taiki-e/create-gh-release-action@v1
        with:
          branch: master
          # (Optional)
          changelog: CHANGELOG.md
          # (Optional) Format of title.
          # [default value: $tag]
          # [possible values: variables $tag, $version, and any string]
          title: $version
          # (Required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: [ create-release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: tools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_PROFILE_RELEASE_LTO: true
